version: "3.8"

services:
  mongo:
    image: mongo:latest
    volumes:
      - ./data/mongo:/data/db
      - /etc/localtime:/etc/localtime:ro
    environment:
      - TZ=Asia/Shanghai
      - MONGO_INITDB_ROOT_USERNAME=tqb-backend
      - MONGO_INITDB_ROOT_PASSWORD=*root password* # 需补充
      - MONGO_INITDB_DATABASE=tqb-backend
    container_name: tqb-backend_mongo
    expose:
      - "27017"
    networks:
      - tqb-backend
  redis:
    image: redis:latest
    expose:
      - "6379"
    environment:
      - TZ=Asia/Shanghai
    container_name: tqb-backend_redis
    volumes:
      - ./data/redis:/data
      - /etc/localtime:/etc/localtime:ro
    tty: true
    networks:
      - tqb-backend
  app:
    build: ./
    volumes:
      - ./env:/env
    environment: 
      - TZ=Asia/Shanghai
      - ENV=default
    container_name: tqb-backend_app
    ports:  
      - "30002:3000" # 设置为自己的端口号
    networks:
      - tqb-backend
    depends_on: 
      - mongo
      - redis
networks:
  tqb-backend:
    driver: overlay
